name: surge.sh deploy

on: workflow_dispatch

jobs:
  surge-deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        environment:
        - example
        - rifadadai
    environment: ${{ matrix.environment }}
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: '20.12.2'
    - run: npm ci
    - run: npm run build
      env:
        NODE_ENV: production
        TITLE: ${{ vars.TITLE }}
        SCRIPT_GOOGLE_URL: ${{ vars.SCRIPT_GOOGLE_URL }}
    - uses: dswistowski/surge-sh-action@v1
      with:
        domain: ${{ vars.DOMAIN }}
        project: ./dist
        login: ${{ vars.SURGE_LOGIN }}
        token: ${{ secrets.SURGE_TOKEN }}

